rules:
  delete_older_than_days: 90

  priority_keywords:
    - job offer
    - interview
    - hiring
    - salary
    - offer letter
    - contract
    - invoice
    - urgent
    - deadline
    - action required

  # Add email addresses or domains you never want emails deleted from
  priority_senders:
    - yorku.ca
    # Canadian banks
    - td.com
    - tdbank.com
    - rbc.com
    - royalbank.com
    - bmo.com
    - scotiabank.com
    - cibc.com
    - eqbank.ca
    - tangerine.ca
    - pcfinancial.ca
    - nbdb.ca
    - desjardins.com
    - simplii.com


automation:
  schedule: daily        # daily or weekly
  max_trash_per_run: 500 # safety cap â€” never trashes more than this per run
